name: RDS
version: 1.6dev
date: 2012-02-16
description: |
    A package for searching relative difference sets

authors:
    - name: Marc Roeder
      url: http://csserver.evansville.edu/~mroeder

maintainers:
    - name: Marc Roeder
      url: http://csserver.evansville.edu/~mroeder

GAP: ">=4.5"

needed-pkgs:
    - name: "DESIGN"
      version: ">=1.3"
      url: "http://www.designtheory.org/software/gap_design/"

suggested-pkgs:
    - name: "AutPGrp"
      version: ">=1.0"
      url: "https://gap-packages.github.io/autpgrp/"

www: http://csserver.evansville.edu/~mroeder
readme: README.rds
packageinfo: http://csserver.evansville.edu/~mroeder/rds/gap4_5/PackageInfo.g

downloads:
    - name: .tar.gz,.tar.bz2,-win.zip
      url: http://csserver.evansville.edu/~mroeder/rds/gap4_5/rds1_6.tar.gz,.tar.bz2,-win.zip

abstract: |
    This package provides functions for the complete enumeration of relative difference sets.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    relative difference sets, finite geometries, projective planes.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Roe12</span>]   <b class='BibAuthor'>Roeder, M.</b>,
     <i class='BibTitle'>RDS, A package for searching relative difference sets,
             Version 1.6dev</i>
     (<span class='BibYear'>2012</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="http://csserver.evansville.edu/~mroeder">http://csserver.evansville.edu/~mroeder</a></span>.
    </p>
    

bibtex: |
    @misc{ RDS1.6dev,
      author =           {Roeder, M.},
      title =            {{RDS}, A package for searching relative difference sets, {V}ersion 1.6dev},
      month =            {Feb},
      year =             {2012},
      note =             {Refereed GAP package},
      howpublished =     {\href {http://csserver.evansville.edu/~mroeder} {\texttt{http://csserver.evansville.edu/}\discretionary {}{}{}\texttt{\texttt{\symbol{126}}mroeder}}},
      keywords =         {relative difference sets; finite geometries; projective planes},
      printedkey =       {Roe12}
    }

