name: RDS
version: 1.8
date: 2022-02-21
description: |
    A package for searching relative difference sets

authors:
    - name: Marc Roeder
      url: http://csserver.evansville.edu/~mroeder

maintainers:
    - name: Marc Roeder
      url: http://csserver.evansville.edu/~mroeder
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.8"

needed-pkgs:
    - name: "DESIGN"
      version: ">=1.3"
      url: "https://gap-packages.github.io/design"

suggested-pkgs:
    - name: "AutPGrp"
      version: ">=1.0"
      url: "https://gap-packages.github.io/autpgrp/"

www: https://gap-packages.github.io/rds/
readme: README.rds
packageinfo: https://gap-packages.github.io/rds/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/rds/releases/download/v1.8/rds-1.8.tar.gz

abstract: |
    This package provides functions for the complete enumeration of relative difference sets.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    relative difference sets, finite geometries, projective planes.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>RT22</span>]   <b class='BibAuthor'>Roeder, M. and GAP Team, T.</b>,
     <i class='BibTitle'>RDS, A package for searching relative difference sets,
             Version 1.8</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/rds/">https://gap-packages.github.io/rds/</a></span>.
    </p>
    

bibtex: |
    @misc{ RDS1.8,
      author =           {Roeder, M. and GAP Team, T.},
      title =            {{RDS},  A  package  for  searching relative difference
                          sets, {V}ersion 1.8},
      month =            {Feb},
      year =             {2022},
      note =             {Refereed GAP package},
      howpublished =     {\href            {https://gap-packages.github.io/rds/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{rds/}}},
      keywords =         {relative    difference    sets;   finite   geometries;
                          projective planes},
      printedkey =       {RT22}
    }

